### ISSUE TITLE
Inclusion request for Conan Center

### ISSUE THREAD

**Issue by danimtb** [piponazo/conan-exiv2#1]
## Inclusion Request Review

This is a review for [Exiv2/0.27@piponazo/stable(piponazo/piponazo)](https://github.com/piponazo/conan-exiv2) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
Exiv2/0.27@piponazo/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated:
  - Please update the recipe to follow the latest recipe conventions as announced [here](https://blog.conan.io/2018/10/11/New-conan-release-1-8.html)
  - Use ``cmake.defintions`` dict to set any CMake definition instead of ``cmake_args``
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library: Please package the license of the library in the ``package()`` method

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
Please update the following Bintray information (unchecked ones).
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

- There are some outdated packages, clean them up with: 
`conan remove Exiv2/0.27@piponazo/testing --outdated -r bincrafters

- There are testing packages that shouldn't be uploaded to Bintray. Please delete them in order to accept the inclusion request.

- There are missing packages for Visual Studio 12, 14 and 15

**Comment by piponazo** [comment]
Thanks for the review! I will work on the changes ASAP

**Comment by piponazo** [comment]
Sorry, the issue get closed automatically after merging the PR. There is still an issue ... the windows packages are not getting uploaded to bintray for some reason. I will investigate.

**Comment by danimtb** [comment]
Don't worry, I will review it again once are the builds are done. Thanks

**Comment by piponazo** [comment]
They are now getting uploaded! 🎉 

```
$ conan search Exiv2/0.27@piponazo/stable -r piponazo -q 'os=Windows'
Existing packages for recipe Exiv2/0.27@piponazo/stable:

Existing recipe in remote 'piponazo':

    Package_ID: 539a1706ae39cfa7d129e2ab48e648bc8b249fc3
        [options]
            buildTool: True
            curl: False
            lensdata: False
            nls: False
            png: True
            shared: False
            ssh: False
            unicode: True
            video: False
            webready: False
            xmp: True
        [settings]
            arch: x86
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 15
            os: Windows
        Outdated from recipe: False

    Package_ID: b7f716472dc87c0679ecbb856f8bf347b51728ff
        [options]
            buildTool: True
            curl: False
            lensdata: False
            nls: False
            png: True
            shared: False
            ssh: False
            unicode: True
            video: False
            webready: False
            xmp: True
        [settings]
            arch: x86
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MT
            compiler.version: 15
            os: Windows
        Outdated from recipe: False

(conan)
```

We need few hours to have all of them there, once this job is finished:
https://ci.appveyor.com/project/piponazo/conan-exiv2

Be aware that the latest changes are in the stable/0.27 branch:
https://github.com/piponazo/conan-exiv2/tree/stable/0.27

**Comment by piponazo** [comment]
The Appveyor finished its job. You'll should see now all the packages.

**Comment by danimtb** [comment]
Included in Conan Center! Thanks a lot 😄
